import type {
  Achievement,
  Certification,
  EducationEntry,
  ExperienceEntry,
  OwnerProfile,
  SkillGroup,
} from "./types";
import { certificateLinks, projectLinks } from "./links";

export const owner: OwnerProfile = {
  photos: [
    { id: "suit", src: "/photos/suit.webp", width: 600, height: 800 },
    { id: "japan", src: "/photos/japan.webp", width: 600, height: 800 },
    { id: "marina", src: "/photos/marina.webp", width: 600, height: 800 },
    { id: "madeira", src: "/photos/madeira.webp", width: 600, height: 800 },
    { id: "cyberpunk", src: "/photos/cyberpunk.webp", width: 600, height: 800 },
  ],
  contacts: [
    { id: "email", kind: "email", value: "lestyshchenko@gmail.com" },
    { id: "phone", kind: "phone", value: "+380734074118" },
    { id: "linkedin", kind: "link", value: "https://www.linkedin.com/in/oleksa-t-90a050a8" },
    { id: "github", kind: "link", value: "https://github.com/froii" },
  ],
};

export const achievements: Achievement[] = [
  { id: "language" },
  { id: "clients" },
  { id: "platform" },
  { id: "payments" },
  { id: "ai" },
  { id: "performance" },
  { id: "review" },
];

export const skills: SkillGroup[] = [
  {
    id: "frontend",
    items: ["React", "Next.js", "TypeScript", "GraphQL", "Apollo Client", "PWA"],
    more: [
      "JavaScript",
      "HTML5",
      "CSS3",
      "SCSS",
      "CSS Modules",
      "styled-components",
      "Ant Design",
      "Storybook",
      "React Router",
    ],
  },
  {
    id: "state",
    items: ["Redux", "Zustand", "React Query"],
    more: ["React Context", "Redux-Saga"],
  },
  {
    id: "backend",
    items: [
      "Node.js",
      "Express",
      "PostgreSQL",
      "NestJS",
      "TypeORM",
      "REST",
      "API design",
      "WebSockets",
      "Redis",
    ],
    more: ["Apollo Server", "type-graphql", "Axios", "Nodemailer"],
  },
  {
    id: "ai",
    items: ["LLM APIs", "RAG", "Prompt Engineering", "AI Agents"],
    more: ["OpenRouter"],
  },
  {
    id: "tools",
    items: ["Docker", "AWS (Cloud Essentials)", "Jenkins", "Git", "ESLint"],
    more: [
      "GitHub Actions",
      "Webpack",
      "Vite",
      "Prettier",
      "Jest",
      "Vitest",
      "React Testing Library",
      "Enzyme",
      "Figma",
      "Jira",
      "Scrum",
    ],
  },
  {
    id: "notable",
    items: [
      "CodeMirror",
      "Lezer",
      "Chevrotain",
      "Lexical",
      "Chart.js",
      "react-dnd",
      "react-window",
      "D3.js",
      "Lodash",
      "Dexie",
      "Puppeteer",
    ],
  },
];

export const experience: ExperienceEntry[] = [
  {
    id: "bechacant",
    organisation: "BechaCant",
    link: projectLinks.bechacant,
    start: "2024-05",
    end: "2026-07",
    techStack: [
      "TypeScript",
      "React",
      "Next.js",
      "PWA",
      "Node.js",
      "NestJS",
      "GraphQL",
      "REST",
      "PostgreSQL",
    ],
    alsoUsed: ["LLM APIs", "RAG", "Push notifications", "In-app purchases", "Git"],
  },
  {
    id: "eteam",
    organisation: "eTeam",
    start: "2021-01",
    end: "2024-11",
    techStack: [
      "React",
      "TypeScript",
      "GraphQL",
      "Apollo Client",
      "Node.js",
      "TypeORM",
      "type-graphql",
      "PostgreSQL",
      "styled-components",
    ],
    alsoUsed: ["CodeMirror", "Lezer", "Chevrotain", "AWS"],
    link: projectLinks.eteam,
  },
  {
    id: "danit",
    nonDev: true,
    organisation: "dan.it",
    start: "2020-09",
    end: "2020-11",
    techStack: ["HTML5", "CSS3", "Git"],
    alsoUsed: [],
  },
  {
    id: "ugenius",
    organisation: "U-Genius Software Development",
    start: "2018-09",
    end: "2021-01",
    techStack: [
      "React",
      "TypeScript",
      "GraphQL",
      "Apollo Server",
      "Redux",
      "Redux-Saga",
      "Ant Design",
      "Ramda",
    ],
    alsoUsed: ["React Router", "useQueryParams", "Storybook", "Jest", "Enzyme", "Docker"],
    link: projectLinks.ugenius,
  },
  {
    id: "adraba",
    organisation: "Adraba",
    start: "2018-01",
    end: "2018-07",
    techStack: ["JavaScript", "SCSS", "Axios", "REST"],
    alsoUsed: ["Ramda", "Jira"],
    link: projectLinks.adraba,
  },
  {
    id: "mackiev",
    organisation: "Software MacKiev",
    start: "2016-09",
    end: "2018-01",
    techStack: ["HTML", "CSS", "JavaScript", "jQuery"],
    alsoUsed: ["Handlebars", "GreenSock"],
    link: projectLinks.mackiev,
  },
  {
    id: "freelance",
    organisation: "FL.ru / Upwork",
    start: "2015-04",
    end: "2016-10",
    techStack: ["HTML", "CSS", "JavaScript", "jQuery"],
    alsoUsed: ["MODX"],
  },
  {
    id: "nas",
    nonDev: true,
    organisation: "National Academy of Sciences of Ukraine",
    start: "2012-01",
    end: "2017-06",
    techStack: ["ArcMap", "Data analysis"],
    alsoUsed: [],
    link: projectLinks.nas,
  },
];

export const education: EducationEntry[] = [
  {
    id: "neoversity",
    institution: "Neoversity IT University",
    start: "2025-09",
    skills: [
      "Machine learning",
      "Neural networks",
      "Algorithms & data structures",
      "Python for data",
      "Statistics",
      "Research methods",
    ],
  },
  {
    id: "nas",
    institution: "National Academy of Sciences of Ukraine",
    start: "2012",
    end: "2016",
    skills: ["Research design", "Data quality & validation", "Technical writing", "ArcMap / GIS"],
  },
  {
    id: "kai",
    institution: "National University \"Kyiv Aviation Institute\"",
    start: "2011",
    end: "2012",
    skills: [
      "Project management",
      "Planning & estimation",
      "Risk management",
      "Global sourcing",
      "Stakeholder communication",
    ],
  },
  {
    id: "shevchenko",
    institution: "Taras Shevchenko National University of Kyiv",
    start: "2007",
    end: "2011",
    skills: [
      "Data analysis",
      "Statistical modelling",
      "Scientific method",
      "GIS",
      "Large datasets",
      "Self-directed learning",
    ],
  },
];

export const certifications: Certification[] = [
  {
    id: "frontendexpert",
    href: certificateLinks.frontendexpert,
  },
  {
    id: "algoexpert",
    href: certificateLinks.algoexpert,
  },
  { id: "english", issued: "2024-02", href: certificateLinks.english },
  {
    id: "aws",
    issued: "2025-08",
    href: certificateLinks.aws,
  },
];
