import type { QuestionTopic } from "./types";

/* Order only; text lives in messages/{locale}/questions.json. */
export const questionTopics: QuestionTopic[] = [
  {
    id: "format",
    items: ["availability", "engagement", "relocation", "trial", "contact"],
  },
  {
    id: "experience",
    items: [
      "focus",
      "recent",
      "clients",
      "leadership",
      "scope",
      "teamSize",
      "hardest",
      "legacy",
      "companyType",
      "domains",
    ],
  },
  {
    id: "motivation",
    items: [
      "whyLooking",
      "idealRole",
      "companyFit",
      "team",
      "interests",
      "growth",
      "track",
      "companySize",
    ],
  },
  {
    id: "stack",
    items: [
      "core",
      "ai",
      "performance",
      "testing",
      "devops",
      "typescript",
      "nextjs",
      "state",
      "backend",
      "systemDesign",
      "mobile",
      "frameworks",
      "accessibility",
      "security",
      "aiTools",
      "auth",
      "realtime",
    ],
  },
  { id: "education", items: ["degrees", "msc", "background", "certifications", "languages"] },
  {
    id: "personal",
    items: [
      "teams",
      "principles",
      "hobbies",
      "conflict",
      "review",
      "estimation",
      "learning",
      "weakness",
      "process",
    ],
  },
  {
    id: "details",
    hidden: true,
    items: [
      "salary",
      "startDate",
      "hours",
      "location",
      "contractTerms",
      "previousJobs",
      "failure",
      "code",
      "references",
      "python",
      "site",
      "tooling",
      "llmStack",
      "payments",
      "pdf",
    ],
  },
];
